### ISSUE TITLE
error 'ELFCLASS32' when starting tensorflow

### ISSUE THREAD

**Issue by bishibashiB** [Qengineering/TensorFlow-Raspberry-Pi_64-bit#1]
HI!
I was lucky finding your walk through for getting a decent version of tensorflow onto a 64bit version of raspbian (on rpi4). Thanks for sharing!
After following the [instructions ](https://qengineering.eu/install-tensorflow-2.2.0-on-raspberry-64-os.html)  I got this error trying to start tf in python. Versions of python is 3.7.3 and gcc 8.3.0. I am installing in a venv.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/env/lib/python3.7/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/home/pi/env/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/pi/env/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/home/pi/env/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
  File "/home/pi/env/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/pi/env/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /home/pi/env/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow.so: wrong ELF class: ELFCLASS32
```

So was this wheel the 64bit-wheel or am I still pointing to some 32-bit stuff somewhere?

**Comment by Qengineering** [comment]
Somehow, somewhere, there is a 32-bit version of TF active, or some snippets. As you already suggested, ELFCLASS32 indicates a 32-bit problem. I've tested the wheel on a clean RPi 4 with 64 OS, without a virtual environment.

**Comment by bishibashiB** [comment]
Thx for your hint! Digged into it and found a temsorflow 0.11.0(?) in my virtual env which would not deinstall via pip. So I manually removed the folders in site-packages.
Also I had to update my protobuf 3.0.0 ->(3.12.0).... (tensorflow install came for me ontop of another install in the environment which probably caused that).
